
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuxuA","is_bot":false,"login":"amisra0","name":""},"headRefName":"AnikaRecRequestDELETE","number":98,"title":"Anika rec request Index Pages Working","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/98"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-Org-Edit","number":91,"title":"LW - organization edit page and tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/91"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-Org-Index","number":89,"title":"LW - Create index page + tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/89"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"Lindsey-UCSBOrg-Create","number":84,"title":"Lindsey ucsb org create page + stories","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/84"}]
