
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"DP-Articles-Form","number":63,"title":"Dp articles form","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/63"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"DP-Articles-fixture","number":62,"title":"Diya- articles fixture","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/62"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"DP-Articles-backend","number":61,"title":"Diya - added article backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/61"}]
