
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"DP-Articles-Placeholder","number":66,"title":"Dp articles placeholder","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/66"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"Liz-UCSBDiningCommonsMenuItem-backend","number":65,"title":"liz - UCSBDiningCommonsMenuItem backend","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/65"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"YS-MenuItemReview-Setup","number":64,"title":"Yuji MenuItemReview - Added backend CRUD API and fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/64"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"DP-Articles-Form","number":63,"title":"Dp articles form","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/63"}]
