
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-5pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-5pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuxuA","is_bot":false,"login":"amisra0","name":""},"headRefName":"AnikaHomework05Assign","number":104,"title":"Anika - Recommendation Request IT and Recommendation Request Web IT","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/104"},{"author":{"id":"MDQ6VXNlcjU1NjAyNjE0","is_bot":false,"login":"jeffsmithepic","name":"Wesley Chiba"},"headRefName":"Wesley-HelpRequest-h05","number":103,"title":"Wesley - HelpRequest IT and Web IT (h05)","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/103"},{"author":{"id":"MDQ6VXNlcjMxNTU0NTUw","is_bot":false,"login":"andyinnie","name":"Andrew Martinez"},"headRefName":"Liz-UCSBDiningCommonsMenuItem-IT","number":102,"title":"Liz - UCSBDiningCommonsMenuItem IT and Web IT (h05)","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/102"},{"author":{"id":"U_kgDOB0qzkg","is_bot":false,"login":"lindseywn","name":""},"headRefName":"LindseyIntegTest","number":101,"title":"Lindsey - Integration & End to End Test","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/101"},{"author":{"id":"U_kgDOBX3DZA","is_bot":false,"login":"yuji-sakaguchi","name":"Yuji Sakaguchi"},"headRefName":"YS-MenuItemReview-HW05","number":100,"title":"Yuji - MenuItemReview HW05 Integration and E2E Testing","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/100"},{"author":{"id":"MDQ6VXNlcjcyNzc3NTIz","is_bot":false,"login":"diyaparm","name":""},"headRefName":"Diya-HW5","number":99,"title":"Diya hw5","url":"https://github.com/ucsb-cs156-s24/team03-s24-5pm-6/pull/99"}]
